services:
  appointment-system:
    build:
      context: ./appointment-system
      dockerfile: ./Dockerfile.dev
    image: lucaschan1020/appointment-system
    env_file:
      - ./appointment-system/.env
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      # - /usr/src/app/dist
      - ./appointment-system:/usr/src/app

  postgres:
    image: postgres:14-alpine
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin4/.env
    ports:
      - '8000:80'
    volumes:
      - ./pgadmin4/data:/var/lib/pgadmin